Add default values for source & tags in config.yml
mn-pollinators/pollinator-facts pull request #121
Opened 2020-07-26 22:01 UTC by UtkarshKr007

When creating a new fact, the preview pane won't render since there is no object with name & url fields on source for .getIn() to find. The tag field also needs to have a array with an empty string as default value since .getIn() is not a function on strings.

2020-07-27 00:06 UTC, floogulinc commented
Maybe we should fix the display code to handle those things missing rather than having defaults like that.

2020-07-27 17:46 UTC, UtkarshKr007 commented
I think it makes sense to use the default option given to us by Netlify cms. since we will never have a fact without a source. When a person creatse a new fact they always are clicking that "Add fact source" button and then typing in a name & url. Instead we can take out the first step, so they just fill the name & url and then add more if they want to via the button.

2020-07-27 20:44 UTC, floogulinc requested changes

2020-07-27 20:44 UTC, floogulinc commented on static/admin/config.yml
> +        default: [""]
```suggestion
        default: []
```

2020-07-29 19:40 UTC, floogulinc approved these changes
I would also like to fix the actual component eventually.

2020-07-29 21:15 UTC, merged