Specify node version Netlify would use to deploy
mn-pollinators/pollinator-facts pull request #206
Opened 2020-12-16 13:22 UTC by UtkarshKr007

Once this is merged in, we can delete the node version from Netlify system environments.

2020-12-16 16:41 UTC, floogulinc requested changes
Why did you pick `.nvmrc` rather than `.node-version`?

2020-12-16 16:41 UTC, floogulinc commented on .nvmrc
> +12.0.0
We don't want to force it to use exactly version `12.0.0`. Setting this to simply `12` would have it use any version 12.

```suggestion
12
```

We may want to just use `lts/*` which has it use the latest LTS version.
```suggestion
lts/*
```

2020-12-17 01:09 UTC, UtkarshKr007 commented
[Netlify Docs](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript) stated they use nvm to fetch the node version we use. Netlify says either `.node-version` or `.nvrmc` is fine, but from what I looked into it didn't seem nvm people added support for `.node-version` yet. These are the issues/PRs I found on nvm's repo regarding this:

https://github.com/nvm-sh/nvm/issues/794
https://github.com/nvm-sh/nvm/pull/1625
https://github.com/nvm-sh/nvm/issues/2292

2020-12-21 22:04 UTC, floogulinc commented
From @UtkarshKr007 

<blockquote>

[Netlify Docs](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript) stated they use nvm to fetch the node version we use and either `.node-version` or `.nvrmc` is fine, but from what I looked into it didn't seem nvm has support for `.node-version` yet. These are the issues/PRs I found on nvm's repo regarding this:

```
https://github.com/nvm-sh/nvm/issues/794
https://github.com/nvm-sh/nvm/pull/1625
https://github.com/nvm-sh/nvm/issues/2292
```

</blockquote>

2020-12-21 22:05 UTC, floogulinc approved these changes

2020-12-21 22:06 UTC, merged