Create Fact “american-plum”
mn-pollinators/pollinator-facts pull request #63
Opened 2020-06-17 20:30 UTC by reuterShawn

Automatically generated by Netlify CMS

2020-06-17 22:25 UTC, floogulinc requested changes

2020-06-17 22:25 UTC, floogulinc commented on src/facts/american-plum.md
> +American plum attracts a variety of bees including bumble, cuckoo, cellophane, mining, and small sweat bees.With it’s highly fragrant flowers, the American Plum offers both pollen and nectar to visit
```suggestion
American plum attracts a variety of bees including bumble, cuckoo, cellophane, mining, and small sweat bees. With its highly fragrant flowers, the American Plum offers both pollen and nectar to visitors.
```

2020-06-17 22:25 UTC, floogulinc commented on src/facts/american-plum.md
> +  url: https://www.flickr.com/photos/28340342@N08
Please link to the specific image, not the user profile.

2020-06-18 04:09 UTC, floogulinc requested changes

2020-06-18 04:09 UTC, floogulinc commented on src/facts/american-plum.md
> +  url: www.flickr.com/photos/28340342@N08/2969269623
Removing the `https://` breaks the link.
```suggestion
  url: https://www.flickr.com/photos/28340342@N08/2969269623
```

2020-06-24 19:23 UTC, floogulinc approved these changes

2020-06-26 00:30 UTC, kklamberty approved these changes

2020-06-26 00:42 UTC, merged