Create Fact “stiff-leaved-goldenrod-1”
mn-pollinators/pollinator-facts pull request #69
Opened 2020-06-17 21:10 UTC by NicolasRobertson

Automatically generated by Netlify CMS

2020-06-17 22:14 UTC, floogulinc requested changes

2020-06-17 22:14 UTC, floogulinc commented on src/facts/stiff-leaved-goldenrod-1.md
> +**This species is more commonly visited by female bees than male, due to it flowering earlier than other goldenrod species (bee book,p. 185)**
Be careful just pasting in from the document

2020-06-17 22:14 UTC, floogulinc commented on src/facts/stiff-leaved-goldenrod-1.md
> +  name: "Bees: An Identification and Native Plant Forage Guide"
No quotes on this please

2020-06-17 22:15 UTC, floogulinc commented on src/facts/stiff-leaved-goldenrod-1.md
> +**This species is more commonly visited by female bees than male, due to it flowering earlier than other goldenrod species (bee book,p. 185)**
It is better to right click and "paste as plain text" and don't include the "(bee book,p. 185)". This shouldn't be bold.

2020-06-17 22:15 UTC, floogulinc commented
I think this can be combined with #69

2020-06-17 22:22 UTC, floogulinc requested changes

2020-06-17 22:22 UTC, floogulinc commented on src/facts/stiff-leaved-goldenrod-1.md
> +  url: https://www.flickr.com/photos/acryptozoo
Please link to the specific image

2020-06-18 22:35 UTC, floogulinc requested changes

2020-06-18 22:35 UTC, floogulinc commented on src/facts/stiff-leaved-goldenrod-1.md
> +category: Plant
Haven't we put the other plants in the "habitat" category?

2020-06-18 22:35 UTC, floogulinc commented on src/facts/stiff-leaved-goldenrod-1.md
> +This species is more commonly visited by female bees than male, due to it flowering earlier than other goldenrod species.
```suggestion
Preferring well-drained soil, stiff-leaved goldenrod is common along roadsides and dry prairies. This species is more commonly visited by female bees than male due to flowering earlier than other goldenrod species.
```

2020-06-18 22:36 UTC, floogulinc requested changes

2020-06-18 22:36 UTC, floogulinc commented on src/facts/stiff-leaved-goldenrod-1.md
> +  license: CC by 2.0
```suggestion
  license: CC BY 2.0
```

2020-06-19 00:23 UTC, floogulinc requested changes
Please rename the file to remove the `-1`

2020-06-26 00:28 UTC, kklamberty requested changes
Please see the previous comment from @floogulinc and act on it.

2020-06-28 10:13 UTC, floogulinc approved these changes
The category is due to change when we switch to tags anyway so it's not important habitat versus plant.

2020-06-29 04:45 UTC, kklamberty approved these changes

2020-06-29 20:08 UTC, merged