Create Fact “wild-bergamot-bee-balm”
mn-pollinators/pollinator-facts pull request #72
Opened 2020-06-18 19:39 UTC by NicolasRobertson

Automatically generated by Netlify CMS

2020-06-18 22:44 UTC, floogulinc requested changes

2020-06-18 22:44 UTC, floogulinc commented on src/facts/wild-bergamot-bee-balm.md
> +title: Wild Bergamot (bee balm)
Can we just call this "Wild Bergamot" and say that its "often called bee balm" in the fact?

2020-06-18 22:44 UTC, floogulinc commented on src/facts/wild-bergamot-bee-balm.md
> +  license: CC by-NC-SA 2.0
```suggestion
  license: CC BY-NC-SA 2.0
```

2020-06-18 22:44 UTC, floogulinc commented on src/facts/wild-bergamot-bee-balm.md
> +Common bees attracted include bumble, digger, long-horned, leaf-cutter, and metallic green sweat bees.
```suggestion
Bees often seek nectar from this flower, though it offers both nectar and pollen. Common bees attracted include bumble, digger, long-horned, leaf-cutter, and metallic green sweat bees.
```

2020-06-19 00:24 UTC, floogulinc requested changes
Please rename the file to just `wild-bergamot.md`

2020-06-26 02:32 UTC, floogulinc requested changes
Please rename the file to just `wild-bergamot.md`

2020-06-28 10:17 UTC, floogulinc approved these changes

2020-06-29 04:27 UTC, kklamberty approved these changes

2020-06-29 20:08 UTC, merged