Create Fact “field-or-pasture-thistle”
mn-pollinators/pollinator-facts pull request #74
Opened 2020-06-18 20:06 UTC by NicolasRobertson

Automatically generated by Netlify CMS

2020-06-18 22:41 UTC, floogulinc requested changes

2020-06-18 22:41 UTC, floogulinc commented on src/facts/field-or-pasture-thistle.md
> +Native thistle attracts a multitude of bees including leaf-cutter, bumble, long-horned, sweat and “small” sweat bees.
```suggestion
An important forage source for all pollinators, field thistle is often mistaken for invasive thistle species, and removed from land. Native thistle attracts a multitude of bees including leaf-cutter, bumble, long-horned, sweat and “small” sweat bees.
```

2020-06-18 22:41 UTC, floogulinc commented on src/facts/field-or-pasture-thistle.md
> +  license: CC by-NC-SA 2.0
```suggestion
  license: CC BY-NC-SA 2.0
```

2020-06-18 22:41 UTC, floogulinc commented on src/facts/field-or-pasture-thistle.md
> +category: Plant
I think we want all category names to be lowercase. Also do we want to have this "plant" category or does it fit "habitat" better?

2020-06-18 22:42 UTC, floogulinc requested changes

2020-06-18 22:42 UTC, floogulinc commented on src/facts/field-or-pasture-thistle.md
> +title: Field or Pasture Thistle
Can we just call this "Field Thistle"

2020-06-19 00:25 UTC, floogulinc requested changes
Please rename the file to just `field-thistle.md`

2020-06-26 02:34 UTC, floogulinc requested changes
Please rename the file to just `field-thistle.md`

2020-06-26 02:34 UTC, floogulinc commented on src/facts/field-or-pasture-thistle.md
> +  license: CC by-NC-SA 2.0
Please do this suggestion.

2020-07-01 20:07 UTC, kklamberty approved these changes

2020-07-03 21:44 UTC, floogulinc approved these changes

2020-07-04 19:29 UTC, merged