Create Fact “bee-nesting-underground”
mn-pollinators/pollinator-facts pull request #76
Opened 2020-06-18 20:42 UTC by NicolasRobertson

Automatically generated by Netlify CMS

2020-06-18 23:00 UTC, floogulinc requested changes

2020-06-18 23:00 UTC, floogulinc commented on src/facts/bee-nesting-underground.md
> +30-40% of bees find cavities to live in, such as hollow branches/stems or dead trees. Inside, they use mud to create chambers for their eggs. Leave fallen trees/branches around your yard to attract b
I think you copied the wrong text here.
```suggestion
60-70% of bees live underground. They like to dig tunnels in sandy soil with nothing growing in it. Attract bees using bare, undisturbed soil around your yard.
```

2020-06-18 23:00 UTC, floogulinc commented on src/facts/bee-nesting-underground.md
> +title: Bee Nesting - Underground
I think we should rename to "Ground Nesting Bees"

2020-06-18 23:00 UTC, floogulinc commented on src/facts/bee-nesting-underground.md
> +  license: CC by 2.0
```suggestion
  license: CC BY 2.0
```

2020-06-18 23:00 UTC, floogulinc commented on src/facts/bee-nesting-underground.md
> +category: Habitat
```suggestion
category: habitat
```

2020-06-18 23:00 UTC, floogulinc commented on src/facts/bee-nesting-underground.md
> +  name: Wild Bee Nests and Building Wild Bee Houses Nesting Habitat
```suggestion
  name: Wild bee nests
```

2020-06-19 00:22 UTC, floogulinc requested changes
Please rename the file to `ground-nesting-bees.md`

2020-06-19 00:22 UTC, floogulinc commented on src/facts/bee-nesting-underground.md
> +  alt: Ground Nesting Bees
The alt text should describe the image rather than just repeat the fact title.

2020-06-28 10:15 UTC, floogulinc requested changes
Please rename the file to `ground-nesting-bees.md`

2020-07-01 20:55 UTC, kklamberty commented on src/facts/bee-nesting-underground.md
> +  alt: Ground Nesting Bees
```suggestion
  alt: Sandy, undisturbed soil with burrows
```

2020-07-01 20:57 UTC, kklamberty reviewed
I made a suggestion about an alt tag for the image that does not just repeat the title (after looking at the image). You can just commit that suggestion if you think it captures the image well.

2020-07-02 16:12 UTC, kklamberty approved these changes
I need to apologize here - I looked back at an outdated request for changes from @floogulinc and you had already changed the alt. You can feel free to use my suggestion or to leave the change as you made it before. I was looking at the wrong version of the world.

2020-07-03 21:49 UTC, floogulinc approved these changes

2020-07-04 19:30 UTC, merged