Create Fact “bee-nesting-cavities”
mn-pollinators/pollinator-facts pull request #77
Opened 2020-06-18 21:03 UTC by NicolasRobertson

Automatically generated by Netlify CMS

2020-06-18 22:54 UTC, floogulinc commented
I think we might want a different image for this one. Maybe one of these: https://pxhere.com/en/photo/1088609 https://pxhere.com/en/photo/1088622

2020-06-18 22:56 UTC, floogulinc requested changes
Please remove unused images.

2020-06-18 22:56 UTC, floogulinc commented on src/facts/bee-nesting-cavities.md
> +title: Bee Nesting - Cavities
I think we should rename it to "Cavity Nesting Bees"

2020-06-18 22:56 UTC, floogulinc commented on src/facts/bee-nesting-cavities.md
> +category: Habitat
```suggestion
category: habitat
```

2020-06-18 22:56 UTC, floogulinc commented on src/facts/bee-nesting-cavities.md
> +  name: Wild Bee Nests and Building Wild Bee Houses Nesting Habitat
```suggestion
  name: Wild bee nests
```

2020-06-18 22:56 UTC, floogulinc commented on src/facts/bee-nesting-cavities.md
> +  license: CC by-NC 2.0
```suggestion
  license: CC BY-NC 2.0
```

2020-06-19 00:20 UTC, floogulinc requested changes
Please rename the file to `cavity-nesting-bees.md` and remove the unused images.

2020-06-19 00:20 UTC, floogulinc commented on src/facts/bee-nesting-cavities.md
> +  name: Wild Bee Nests
```suggestion
  name: Wild bee nests
```
That is how they have it on the souce page.

2020-06-19 00:20 UTC, floogulinc commented on src/facts/bee-nesting-cavities.md
> +30-40% of bees find cavities to live in, such as hollow branches/stems or dead trees. Inside, they use mud to create chambers for their eggs. Leave fallen trees/branches around your yard to attract b
>Leave fallen trees/branches around your yard to attract bees.

I don't know if this is the right thing to say looking at the source.

2020-07-01 20:06 UTC, kklamberty requested changes
Looking at the source, it seems like the undisturbed ground was emphasized more

2020-07-01 20:06 UTC, kklamberty commented on src/facts/cavity-nesting-bees.md
> +30-40% of bees find cavities to live in, such as hollow branches/stems or dead trees. Inside, they use mud to create chambers for their eggs. Leave fallen trees/branches around your yard to attract b
```suggestion
30-40% of bees find cavities to live in, such as hollow branches/stems or dead trees. Inside, they use mud to create chambers for their eggs. Leave fallen trees/branches and areas of undisturbed ground around your yard to attract bees.
```

2020-07-01 21:05 UTC, kklamberty approved these changes

2020-07-03 21:44 UTC, floogulinc approved these changes

2020-07-04 19:35 UTC, merged