Replace fact categories with tags
mn-pollinators/pollinator-facts pull request #96
Opened 2020-06-24 18:52 UTC by UtkarshKr007

We have been sorting facts into categories like 'habitat' and 'behavior', but not all facts can be easily categorized into a single criteria.A category like 'habitat' can contain facts about both 'plants' and 'homes' associated with pollinators which is why we are switching to tags. Tags will allow a fact to be associated with multiple criteria while being general enough, but not as encompassing as a category.

2020-06-25 05:18 UTC, UtkarshKr007 commented
Worked with @NicolasRobertson on the previous commit. Included the co-author in the commit, but the he is not being credited on the commit for some reason.

2020-07-06 07:46 UTC, floogulinc requested changes
I have made some tweaks that are too much to do in suggestions here so I made another branch and a PR to this branch: https://github.com/mn-pollinators/pollinator-facts/pull/111

2020-07-06 07:46 UTC, floogulinc commented on src/components/large-fact-card.js
> +          </Grid>
This should all be in a single `<Grid item>` or we get this:

![image](https://user-images.githubusercontent.com/1300395/86565397-5d6bc980-bf2d-11ea-8827-d7e0d18c3a66.png)

2020-07-06 07:50 UTC, floogulinc commented on src/components/tag.js
> +    backgroundColor: '#D3D3D3',
I don't think we need to set this slightly darker grey. The default is fine.

2020-07-15 19:33 UTC, floogulinc commented
Example from today's discussion:
```ts
allPosts.filter(post => searchTags.every(st => post.tags.includes(st)))
```

2020-07-15 19:38 UTC, floogulinc commented on src/components/large-fact-card.js
> +    marginBottom: '8px',
```suggestion
    marginBottom: '12px',
```

2020-07-19 02:40 UTC, floogulinc approved these changes
I think we might want to tweak what tags some of the facts have (eg should flowers get both `habitat` and `plant` (or maybe `flower`)) but other than that it looks good.

2020-07-19 20:28 UTC, merged