Implement a related facts component
mn-pollinators/pollinator-facts pull request #97
Opened 2020-06-29 18:04 UTC by UtkarshKr007

We are using [gatsby-remark-related-posts](https://www.gatsbyjs.org/packages/gatsby-remark-related-posts/) plugin which calculates the similarity between fact texts [tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) and [Cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity).

2020-06-29 18:31 UTC, floogulinc commented
I dont know if this way of finding related facts is what we want considering we are adding tags.

2020-06-29 18:53 UTC, UtkarshKr007 commented
I believe we thought it would be interesting to see what facts seem to be related by their text similarity albeit having different categories/tags. I personally didn't notice any discernible pattern of certain facts being related to others while totally different from others, but that's probably in part to the low count of facts we have. 
While it makes sense to scrap this method and implement one that groups related facts by the number of tags they share or something similar, I am kind of interested what this finds to be related once given a large list of facts.

2020-07-08 19:26 UTC, floogulinc requested changes

2020-07-08 19:26 UTC, floogulinc commented on src/components/horizontal-fact-card.js
> +                    <Typography component="h6" variant="h6">
```suggestion
                    <Typography component="h3" variant="h6">
```

2020-07-08 19:26 UTC, floogulinc commented on src/components/horizontal-fact-card.js
> +                    <Typography>
This should be variant `body2` I think.

2020-07-08 19:26 UTC, floogulinc commented on src/components/horizontal-fact-card.js
> +        marginBottom: '5px',
This margin should be handled in the component using it and should be more like `16px`

2020-07-08 19:26 UTC, floogulinc commented on src/templates/factTemplate.js
> +        <h2>Related Facts</h2>
This should be a `Typography` component.

2020-07-08 19:26 UTC, floogulinc commented on src/templates/factTemplate.js
> +                  fixed(width: 100, height: 100) {
We decided to try having this image be `fluid` with a max width of `100`.

2020-07-16 18:36 UTC, floogulinc commented
Are the related facts being ordered by relatedness? They all seem to be the same 3-4.

2020-07-25 10:04 UTC, floogulinc approved these changes
Looks like you need to fix the merge conflicts with master

2020-07-25 10:04 UTC, floogulinc commented on src/templates/factTemplate.js
> +        <Typography variant="h6" component="h3" className={classes.relatedFactsTitle} > Related Facts </Typography>
```suggestion
        <Typography variant="h6" component="h3" className={classes.relatedFactsTitle}>Related Facts</Typography>
```

2020-07-25 20:48 UTC, merged